
# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: 'codelab-monitor'

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
# - "first.rules"
# - "second.rules"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus-service'
    static_configs:
      - targets: ['prometheus-service:9090']

  - job_name: 'gateway-service'
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:5000']
      #- targets: ['account-service:8080']

  - job_name: 'security-service'
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:5001']
      #- targets: ['account-service:8080']

  - job_name: 'account-service'
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:5002']
      #- targets: ['account-service:8080']

  - job_name: 'deposit-service'
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:5003']
      #- targets: ['account-service:8080']

  - job_name: 'withdrawal-service'
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:5004']
      #- targets: ['account-service:8080']

  - job_name: 'history-service'
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:5005']
      #- targets: ['account-service:8080']

  - job_name: 'notification-service'
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:5006']
      #- targets: ['account-service:8080']